Note4all/urls.py
# from django.conf.urls import include, url
from django.contrib import admin
from django.urls import include, re_path

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'', include(('mynote.urls', 'mynote'), namespace='mynote')),
    re_path(r'^users/', include(('users.urls', 'users'), namespace='users')),
    
]

mynote/urls.py
"""Defines urls patterns for note4all."""

# from django.conf.urls import url
from . import views
from django.urls import include, re_path

urlpatterns = [
    #homepage
    re_path(r'^$', views.index, name='index'),
    #courses page
    re_path(r'^course/$', views.courses, name='courses'),
    #topics of a course page
    re_path(r'^courses/(?P<course_id>\d+)/$', views.course, name='course'),
    #notes of a topic page
    re_path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    #page for adding a new course
    re_path(r'^new_course/$', views.new_course, name='new_course'),
    #page for adding a new topic
    re_path(r'^new_topic/(?P<course_id>\d+)/$', views.new_topic, name='new_topic'),
    #page for editing a topic
    re_path(r'^edit_topic/(?P<topic_id>\d+)/$', views.edit_topic, name='edit_topic'),
    #page for adding new notes
    re_path(r'^new_note/(?P<topic_id>\d+)/$', views.new_note, name='new_note'),
    #page for editing notes
    re_path(r'^edit_note/(?P<note_id>\d+)/$', views.edit_note, name='edit_note'),

]

users/urls.py
"""Defines urls patterns for users."""

from django.urls import include, re_path
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    #login page
    re_path(r'^login/$', LoginView.as_view(template_name='users/login.html'),
            name='login'),
    re_path(r'^logout/$', views.logout_view, name='logout'),
    re_path(r'^register/$', views.register, name='register'),
    
]

mynote/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Course(models.Model):
    """Course subject the user is taking."""
    course = models.CharField(max_length=100)
    date_started = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    public = False

    def __str__(self):
        """Return a string representation of the model."""
        return self.course

class Topic(models.Model):
    """Topic the user is learning."""
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.CharField(max_length=100)
    date_started = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Returns a string representation of the model."""
        return self.topic

class Note(models.Model):
    """Notes about a topic"""
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    notes = models.TextField()
    date_started = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Returns a string representation of the model."""
        if len(self.notes) > 250:
            displaynotes = self.notes[:100] + "..."
        else:
            displaynotes = self.notes
        return displaynotes

mynote/forms.py
from django import forms
from .models import Course, Topic, Note


class Courseform(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course']
        labels = {'text': ''}

class Topicform(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['topic']
        labels = {'text': ''}

class Noteform(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['notes']
        labels = {'text': ''}
        widgets = {'notes': forms.Textarea(attrs={'cols':80})}

mynote/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Course, Topic, Note
from .forms import Courseform, Topicform, Noteform

def ensure_is_user(item, request):
    """Ensures data is only accessible to current user"""
    if item.owner != request.user:
        raise Http404

def index(request):
    """Shows the homepage  for note4all"""
    return render(request, "mynote/index.html")

@login_required
def courses(request):
    """Show all courses."""
    courses = Course.objects.filter(owner=request.user).order_by('date_started')
    context = {'courses': courses}
    return render(request, 'mynote/course.html', context)

@login_required
def course(request, course_id):
    """Show a single course and all it's topics."""
    course = get_object_or_404(Course, id=course_id)

    #making sure its only accessible to current user
    ensure_is_user(course, request)

    topics = course.topic_set.order_by('-date_started')
    context = {'course': course, 'topics': topics}
    return render(request, 'mynote/topic.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and it's notes."""
    topic = get_object_or_404(Topic, id=topic_id)
    notes = topic.note_set.order_by('-date_started')
    context = {'topic': topic, 'notes': notes}
    return render(request, 'mynote/note.html', context)

@login_required
def new_course(request):
    """Add a new course"""
    if request.method != 'POST':
        #creates a blank form
        form = Courseform()
    else:
        #process/POST submitted data
        form = Courseform(request.POST)
        if form.is_valid():
            new_course = form.save(commit=False)
            new_course.owner = request.user
            new_course.save()
            return HttpResponseRedirect(reverse('mynote:courses'))
    context = {'form': form}
    return render(request, 'mynote/new_course.html', context)

@login_required
def new_topic(request, course_id):
    """Add a new topic per course"""
    course = Course.objects.get(id=course_id)

    if request.method != 'POST':
        #creates a blank form
        form = Topicform()
    else:
        #process/POST submitted data
        form = Topicform(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.course = course
            new_topic.save()
            return HttpResponseRedirect(reverse('mynote:course',
                                        args=[course_id]))
    context = {'course': course, 'form': form}
    return render(request, 'mynote/new_topic.html', context)

@login_required
def edit_topic(request, topic_id):
    """Edit a topic"""
    topic = Topic.objects.get(id=topic_id)
    course = topic.course

    ensure_is_user(topic, request)

    if request.method != 'POST':
        #initial request; pre-fill form with the current topic
        form = Topicform(instance=topic)
    else:
        #process/POST submitted data
        form = Topicform(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mynote:course',
                                        args=[topic_id]))
    context = {'topic': topic, 'course': course, 'form': form}
    return render(request, 'mynote/edit_topic.html', context)

@login_required
def new_note(request, topic_id):
    """Add new notes per topic"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        #creates a blank form
        form = Noteform()
    else:
        #process/POST submitted data
        form = Noteform(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.topic = topic
            new_note.save()
            return HttpResponseRedirect(reverse('mynote:topic',
                                        args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'mynote/new_note.html', context)

@login_required
def edit_note(request, note_id):
    """Editing notes"""
    note = Note.objects.get(id=note_id)
    topic = note.topic

    ensure_is_user(note, request)

    if request.method != 'POST':
        #initial request; pre-fill form with the current note
        form = Noteform(instance=note)
    else:
        #process/POST submitted data
        form = Noteform(instance=note, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mynote:topic',
                                        args=[note_id]))
    context = {'note': note, 'topic': topic, 'form': form}
    return render(request, 'mynote/edit_note.html', context)

mynote/templates/mynote/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <title>Note4all</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>

  <body>
    <!--Static navbar-->

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'mynote:index' %}">Note4all</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'mynote:courses' %}">Course</a></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">Log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">Register</a></li>
              <li><a href="{% url 'users:login' %}">Login</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse-->
      </div>
    </nav>

    <div class="container">
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div> <!--/container-->
  </body>
</html>

mynote/templates/mynote/course.html
{% extends "mynote/base.html" %}

{% block header %}
  <small>
    <h4><a href="{% url 'mynote:new_course' %}">New course?</a></h4>
  </small>
  <h1>
    Your courses
  </h1>
  {% endblock header%}

{% block content %}

<ul>
    {% for course in courses %}
      <li>
        <h3>
          <a href="{% url 'mynote:course' course.id %}">{{ course }}</a>
        </h3>
      </li>
    {% empty %}
      <li>No course have been added yet.</li>
    {% endfor %}
    
</ul>
<p>Note: You cannot edit after adding.</p>

{% endblock content %}

mynote/templates/mynote/edit_note.html
{% extends "mynote/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>
    <a href="{% url 'mynote:topic' topic.id %}">{{ topic }}</a>
  </h2>
{% endblock header %}

{% block content %}
  <font size="+2">
    <p>Edit note:</p>
  </font>
  <form action="{% url 'mynote:edit_note' note.id %}" method="post"
        class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
          <button name="submit" class="btn btn-primary">Save</button>
        {% endbuttons %}
     </form>
{% endblock content %}

mynote/templates/mynote/edit_topic.html
{% extends "mynote/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>
    <a href="{% url 'mynote:course' course.id %}">{{ course }}</a>
  </h2>
{% endblock header %}

{% block content %}
  <font size="+2">
    <p>Edit topic:</p>
  </font>
  <form action="{% url 'mynote:edit_topic' topic.id %}" method="post"
        class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
          <button name="submit" class="btn btn-primary">Save Changes</button>
        {% endbuttons %}
  </form>
{% endblock content %}

mynote/templates/mynote/index.html
{% extends "mynote/base.html" %}

{% block header %}
  <div class="jumbotron">
    <h1>Note For All.</h1>
    <h5>The Best Jottings</h5>
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to join the
    the users of this awesome note.
  </h2>
  <p>
    Summarize your learnings with the best note you never knew you needed.
  </p>
{% endblock content %}

mynote/templates/mynote/new_course.html
{% extends "mynote/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add Course:</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'mynote:new_course' %}" method="post"
        class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
          <button name="submit" class="btn btn-primary">Add course</button>
        {% endbuttons %}
    </form>
{% endblock content %}

mynote/templates/mynote/new_note.html
{% extends "mynote/base.html" %}
{% block content %}

<p>
    <a href="{% url 'mynote:topic' topic.id %}">{{ topic }}</a>
</p>

<p>Write notes:</p>
    <form action="{% url 'mynote:new_note' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add Note</button>
    </form>
{% endblock content %}

mynote/templates/mynote/new_topic.html
{% extends "mynote/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>
    <a href="{% url 'mynote:course' course.id %}">{{ course }}</a>
  </h2>
{% endblock header %}

{% block content %}

  <font size="+2">
    <p>Add a new topic:</p>
  </font>
  <form action="{% url 'mynote:new_topic' course.id %}" method="post"
        class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
          <button name="submit" class="btn btn-primary">Save</button>
        {% endbuttons %}
  </form>
{% endblock content %}

mynote/templates/mynote/note.html
{% extends "mynote/base.html" %}

{% block header %}
 <h2>Topic: {{ topic }}</h2>
{% endblock header %}

{% block content %}
<p>
  <a href="{% url 'mynote:new_note' topic.id %}">Write notes</a>
</p>

{% for note in notes %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>
      {{ note.date_started|date:'M d, Y H:i' }}
      <small class="panel">
        <a href="{% url 'mynote:edit_note' note.id %}">Edit Note</a>
      </small>
    </h4>
  </div>
  <div class="panel-body">
    {{ note.notes|linebreaks }}
  </div>
</div> <!-- panel -->

{% empty %}
  <h3>No notes for this topic.</h3>

{% endfor %}
{% endblock content %}

mynote/templates/mynote/topic.html
{% extends "mynote/base.html" %}

{% block header %}
  <h1>Course: {{ course }}</h1>
{% endblock header%}

{% block content %}

<h2>Topics:</h2>

    {% for topic in topics %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>
            {{ topic.date_started|date:'M d, Y H:i' }}
          </h4>
          <small class="panel">
            <a href="{% url 'mynote:edit_topic' topic.id %}">edit topic</a>
          </small>
        </div>
        <div class="panel-body">
          <font size="+1">
            <a href="{% url 'mynote:topic' topic.id %}">{{ topic }}</a>
          </font>
        </div>
      </div> <!-- panel -->
    {% empty %}
      <h3>No topic for this course.</h3>
    {% endfor %}

<p>
  <h3><a href="{% url 'mynote:new_topic' course.id %}">New Topic</a></h3>
</p>
{% endblock content %}